// Re-export shared types for frontend use
export type {
	Poll,
	VoteMessage,
	PollUpdateMessage,
	RoomMetadata,
	RoomListRequestMessage,
	RoomListMessage,
	Message,
	CreatePollResponse,
	GetPollResponse,
	RegisterRoomResponse,
	ApiErrorResponse,
	// Game-related types
	GameSession,
	GameMetadata,
	GameListRequestMessage,
	GameListMessage,
	GameChoiceMessage,
	GameUpdateMessage,
	PlayerJoinMessage,
	PlayerJoinedMessage,
	PlayerLeftMessage,
	VotingStartedMessage,
	VotingEndedMessage,
	SceneTransitionMessage,
	GameCompletedMessage,
	GameErrorMessage,
	CharacterState,
	StoryChoice,
	StoryScene,
	StoryTemplate,
	VoteResult,
	CreateGameResponse,
	GetGameResponse,
	GetStoriesResponse,
	JoinGameResponse
} from '$shared/schemas';
